apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: karsajobs-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.11-management
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: amqp
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - rabbitmq-diagnostics ping
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /data/rabbitmq
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
