apiVersion: apps/v1  # Specifies the API version for this Kubernetes resource, which is the apps/v1 version.
kind: StatefulSet  # Defines the type of Kubernetes resource, which is a StatefulSet for managing stateful applications.
metadata:
  name: rabbitmq  # Specifies the name of the StatefulSet resource, which is "rabbitmq."
  namespace: karsajobs-ns  # Specifies the Kubernetes namespace where this StatefulSet will be created.
spec:
  replicas: 1  # Specifies the desired number of replicas, in this case, 1.
  selector:
    matchLabels:
      app: rabbitmq  # Selects Pods to be controlled by this StatefulSet based on the label "app: rabbitmq."
  serviceName: rabbitmq  # Specifies the service name used to access the StatefulSet's Pods.
  template:
    metadata:
      labels:
        app: rabbitmq  # Specifies labels to be applied to the Pods created by this StatefulSet.
    spec:
      containers:
      - image: rabbitmq:3.11-management  # Specifies the Docker image to use for the container.
        name: rabbitmq  # Specifies the name of the container within the Pod.
        ports:
        - containerPort: 5672  # Specifies the port on which the container listens for RabbitMQ (5672).
          name: amqp  # Assigns a name "amqp" to this port.
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - rabbitmq-diagnostics ping
          initialDelaySeconds: 10  # Specifies the initial delay before the readiness probe is initiated.
          periodSeconds: 10  # Specifies how often the probe is performed.
          timeoutSeconds: 5  # Specifies the maximum time for the probe to be successful.
        volumeMounts:
        - mountPath: /data/rabbitmq  # Mounts a volume at the specified path within the container.
          name: data-volume  # Associates the volume mount with the named volume "data-volume."
      volumes:
      - name: data-volume  # Defines the volume to be used in the Pod.
        persistentVolumeClaim:
          claimName: rabbitmq-pvc  # Specifies the PersistentVolumeClaim to be used for this volume.