apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-virtual-service
  namespace: karsajobs-ns
spec:
  hosts:
    - '*'
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            exact: /order
      route:
        - destination:
            host: order-service
            port:
              number: 3000