apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: karsajobs-ns
spec:
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - env:
        - name: PORT
          value: "3001"
        - name: AMQP_URL
          value: amqp://rabbitmq-service.default.svc.cluster.local:5672
        image: ghcr.io/mirfani340/devops-dicoding-3/shipping-services:v1
        name: shipping
        ports:
        - containerPort: 3001
