apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: karsajobs-ns
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      name: http-order
      port: 3000
      targetPort: 3000